### ISSUE TITLE
Errors from startup are hidden by ora

### ISSUE THREAD

**Issue by Sleavely** [Sleavely/exodus-migrations#26]
When an error occurs before a migration file has begun running - such as when `context` from the configuration file fails - the `ora` spinners fail to.. uhh.. fail().

Actual CLI output:

```
$ npx exodus migrate

TypeError: Cannot read property 'fail' of undefined
    at C:\Git\<someProject>\node_modules\exodus\bin\cli.js:79:29
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

  Usage
    $ exodus <action>

  Possible actions
    init              Adds a config file in your project directory
    create <name>     Creates a new file in your migrations dir
    migrate           Runs all remaining migrations

  Options
    --help

  For more information, see:
  https://github.com/Sleavely/exodus-migrations
```

The output should look more along the lines of

```
$ npx exodus migrate

Error: Whoops! The bla bla bla thing failed to blabla
    at async Object.exports.context (C:\Git\<someProject>\exodus.config.js:19:36)
    at async C:\Git\<someProject>\node_modules\exodus\bin\cli.js:67:33
```

**Comment by Sleavely** [comment]
This is what output looks like now:

![](https://i.imgur.com/BGjuGMU.png)
